//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTopic
    {
        public int topicID { get; set; }
        public string topictitle { get; set; }
        public string topicDescription { get; set; }
        public string topicIcon { get; set; }
    }
}
